identity:
    database:
        DATABASES:
            default:
              username: {user_name}
              password: {password}
              db: identity
              host: mongodb://{mongodb_server_ip}
              read_preference: PRIMARY

secret:
    database:
        DATABASES:
            default:
              username: {user_name}
              password: {password}
              db: secret
              host: mongodb://{mongodb_server_ip}
              read_preference: PRIMARY

repository:
    database:
        DATABASES:
            default:
              username: {user_name}
              password: {password}
              db: repository
              host: mongodb://{mongodb_server_ip}
              read_preference: PRIMARY

plugin:
    database:
        DATABASES:
            default:
              username: {user_name}
              password: {password}
              db: plugin
              host: mongodb://{mongodb_server_ip}
              read_preference: PRIMARY

config:
    database:
        DATABASES:
            default:
              username: {user_name}
              password: {password}
              db: config
              host: mongodb://{mongodb_server_ip}
              read_preference: PRIMARY

inventory:
    database:
        DATABASES:
            default:
              username: {user_name}
              password: {password}
              db: inventory
              host: mongodb://{mongodb_server_ip}
              read_preference: PRIMARY

monitoring:
    database:
        DATABASES:
            default:
              username: {user_name}
              password: {password}
              db: monitoring
              host: mongodb://{mongodb_server_ip}
              read_preference: PRIMARY

statistics:
    database:
        DATABASES:
            default:
              username: {user_name}
              password: {password}
              db: statistics
              host: mongodb://{mongodb_server_ip}
              read_preference: PRIMARY

billing:
    database:
        DATABASES:
            default:
              username: {user_name}
              password: {password}
              db: billing
              host: mongodb://{mongodb_server_ip}
              read_preference: PRIMARY

notification:
    database:
        DATABASES:
            default:
              username: {user_name}
              password: {password}
              db: notification
              host: mongodb://{mongodb_server_ip}
              read_preference: PRIMARY

cost-analysis:
    database:
        DATABASES:
            default:
              username: {user_name} 
              password: {password} 
              db: cost-analysis
              host: mongodb://{mongodb_server_ip} 
              port: 27017
              read_preference: PRIMARY

board:
    database:
        DATABASES:
            default:
              username: {user_name} 
              password: {password} 
              db: board
              host: mongodb://{mongodb_server_ip} 
              port: 27017
              read_preference: PRIMARY

file-manager:
    database:
        DATABASES:
            default:
              username: {user_name} 
              password: {password} 
              db: file-manager
              host: mongodb://{mongodb_server_ip} 
              port: 27017
              read_preference: PRIMARY

dashboard:
    database:
        DATABASES:
            default:
              username: {user_name} 
              password: {password} 
              db: dashboard
              host: mongodb://{mongodb_server_ip} 
              port: 27017
              read_preference: PRIMARY
